In [2]:
import numpy as np

In [3]:
Listarray=np.array([[3,2,3],[2,4,5]],np.int64)

In [5]:
Listarray.dtype


dtype('int64')

In [6]:
Listarray.size

6

In [7]:
Listarray.sort()


In [8]:
Listarray


array([[2, 3, 3],
       [2, 4, 5]], dtype=int64)

In [9]:
Listarray[0,1]=9

In [10]:
Listarray

array([[2, 9, 3],
       [2, 4, 5]], dtype=int64)

In [12]:
book=np.array([2,3,4])

In [13]:
pre_re=np.mean(book)

In [14]:
res=np.std(book)

In [17]:
print(":",pre_re)



: 3.0


In [18]:
ok=np.array([[3,4,4],[4,3,2]])

In [19]:
scalar=90

In [20]:
broadcasted=ok+scalar

In [21]:
print(broadcasted)

[[93 94 94]
 [94 93 92]]


In [22]:
broadcasted.shape

(2, 3)

In [24]:
broadcasted.ravel()

array([93, 94, 94, 94, 93, 92])

In [25]:
broadcasted.argmax()


1

In [26]:
time_series = np.array([0, 1, 0, -1])
fft_result = np.fft.fft(time_series)
print(fft_result)
# Output: Fourier Transform of the input array


[0.+0.j 0.-2.j 0.+0.j 0.+2.j]


In [35]:
kk=np.array([[2,3],[8,0]])

In [36]:
np.dot(kk,kk)

array([[28,  6],
       [16, 24]])

In [37]:
kk.T

array([[2, 8],
       [3, 0]])

In [58]:
yy=np.array([[1,24,3],[2,9,0]])

In [40]:
ar=np.array(yy)

In [41]:
ar

array([[ 1, 24,  3],
       [ 2,  9,  0]])

In [43]:
ar.sum(axis=0)

array([ 3, 33,  3])

In [44]:
ar.T

array([[ 1,  2],
       [24,  9],
       [ 3,  0]])

In [45]:
ar.flat

In [46]:
ar

array([[ 1, 24,  3],
       [ 2,  9,  0]])

In [47]:
ar.flat

In [48]:
ar

array([[ 1, 24,  3],
       [ 2,  9,  0]])

In [49]:
ar.flatten

<function ndarray.flatten>

In [50]:
ar

array([[ 1, 24,  3],
       [ 2,  9,  0]])

In [51]:
for items in ar.flat:
    print(items)

1
24
3
2
9
0


In [52]:
ar.ndim

2

In [59]:
yy.nbytes

24

In [55]:
ar.reshape(2,3)

array([[ 1, 24,  3],
       [ 2,  9,  0]])

In [57]:
ar.ravel()

array([ 1, 24,  3,  2,  9,  0])

In [69]:
array=np.array([1,2,3,4])

In [72]:
array2=np.array([9,98,1,2])

In [62]:
r=array*array2

In [63]:
m=r-1

In [66]:
np.dot(r,m)

134

In [4]:
jj=np.random.rand(3,3)


In [68]:
jj

array([[0.18087532, 0.62364294, 0.60655341],
       [0.49816958, 0.25507362, 0.10860489],
       [0.3027928 , 0.48260741, 0.2774404 ]])

In [73]:
np.divide(array,array2)

array([0.11111111, 0.02040816, 3.        , 2.        ])