In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,9,5,6]],np.int8)

In [3]:
myarr[0,1]

9

In [4]:
myarr

array([[3, 9, 5, 6]], dtype=int8)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.sort()

In [7]:
myarr

array([[3, 5, 6, 9]], dtype=int8)

In [8]:
myarr.dtype

dtype('int8')

In [9]:
myarr[0,1]=45

In [10]:
myarr

array([[ 3, 45,  6,  9]], dtype=int8)